### ISSUE TITLE
Horizontal Chart with Alternating colors

### ISSUE THREAD

**Issue by lsamaria** [Kolch/Charts#1]
How can I use this to make 1 horizontal chart with alternating colors. For example I have UISlider, as it scrubs I want to change the colors of 1 bar chart to alternating colors. If the slider value is 0.2-0.4 it'll be red, 0.4-0.7 blue, 0.7 to 1 red. Those are just example values, the actual values and colors will vary. So the bar will be multicolored.

Something like this. The colors are based on where the slider starts and stops.

![Screen Shot 2022-03-21 at 8 44 57 PM](https://user-images.githubusercontent.com/15787990/159385654-71e46037-270c-42c2-bcd2-8db8feecae95.png)

**Comment by Kolch** [comment]
Didn't understood completely your task. But I added InlineChart, hope that will help you. You can see it in [Inline branch](https://github.com/Kolch/Charts/tree/InlineChart). See the file [InlineChartVC](https://github.com/Kolch/Charts/blob/InlineChart/Charts/UI/Controllers/InlineChartVC.swift). 

It looks something like this:
![IMG_B4DB26213EEF-1](https://user-images.githubusercontent.com/6265818/159451244-d2a09018-e97d-422f-9ae9-86f853b5b00e.jpeg)



Hope it has what you were looking for. I close this issue. If you will have any questions let me know!

**Comment by lsamaria** [comment]
Sorry for the late reply, was working on some serious bugs.

That looks FANTASTIC!!! Thanks :)

I starred your repo!
